### ISSUE TITLE
Help for consume the api via jquery

### ISSUE THREAD

**Issue by mamiaro** [igdb/api#15]
Hi, i start using this https://api-2445582011268.apicast.io instead mashape api.. but i can't make it work.. i think my headers are wrong.. any help, or example with the method to do the ajax ?

**Comment by sharpless512** [comment]
Take a look here at the top example:

https://igdb.github.io/api/examples/

Example of your headers

```
.header("user-key", "YOUR_KEY")
.header("Accept", "application/json")
```

**Comment by Szasza** [comment]
Hi @mamiaro,

In general it is a bad idea to expose your API key on the front-end by using jQuery due to multiple reasons. I would like to recommend to put together a small backend app which takes the role of a proxy.

That being said, for the sake of answering the question, here is how it can be done:
```
$.ajax({
    type: 'GET',
    url: 'https://api.....',
    headers: {
        'user-key': 'YOURAPIKEYHERE',
        'Accept': 'application/json'
    }
}).done(function (response) {
    console.log(response);
});
```

**Comment by krazyjakee** [comment]
Sorry all, actually due to Cross-origin resource sharing restrictions, front-end javascript cannot utilise the API. @Szasza was right, you will need to create a back-end proxy that will not only shield your API key but also allow you to cache responses and reduce requests to the API.
